### ISSUE TITLE
Merge with poetry?

### ISSUE THREAD

**Issue by mauricekraus** [bennylut/relaxed-poetry#1]
Is there any way that some of these changes will be introduced back into poetry or will this repo stay seperated?

**Comment by bennylut** [comment]
Hi,
When I'll have a little time, I can offer some merge requests to the poetry core team if those changes are not too far apart from poetry's code base (and ideology). 

What are the changes that you are interested in?

About the separation of this repo from the original poetry - I believe that at this stage, the code bases are too far apart, I am working on major refactoring on poetry's code base in order to improve speed and to achieve a better workflow (in my eyes) and it will make it even harder to merge the repositories. This why I am planning to eventually move this repo into its own project and not a fork..

**Comment by mauricekraus** [comment]
Especially support for local versions (aka pytorch+cuda), profiles and support for multiple packages. I will try to give your project a shot. If this works out for me and there is a clear roadmap with some good first issues I would also like to contribute to the project/fork.

**Comment by bennylut** [comment]
@mauricekraus, 
Great, while It is still in its early stage I will be more than happy to hear if there are any problems you encounter
